"""Decision context model containing evaluation results."""

from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


class AlertSeverity(str, Enum):
    """Severity levels for clinical alerts."""
    CRITICAL = "critical"  # Absolute contraindication
    HIGH = "high"          # Strong warning, requires intervention
    MODERATE = "moderate"  # Caution advised
    LOW = "low"            # Informational


class Alert(BaseModel):
    """
    Clinical alert generated by rule evaluation.

    Attributes:
        message: Human-readable alert message
        severity: Alert severity level
        rule_name: Name of the rule that generated this alert
        category: Alert category (e.g., 'cardiac', 'renal', 'interaction')
    """
    message: str = Field(..., description="Alert message")
    severity: AlertSeverity = Field(..., description="Alert severity")
    rule_name: str = Field(..., description="Triggering rule name")
    category: str = Field(..., description="Alert category")


class DoseAdjustment(BaseModel):
    """Recommended dose adjustment."""
    original_dose: Optional[str] = Field(None, description="Standard dose")
    adjusted_dose: str = Field(..., description="Recommended adjusted dose")
    reason: str = Field(..., description="Reason for adjustment")


class DecisionContext(BaseModel):
    """
    Decision output from rule engine evaluation.

    Attributes:
        contraindicated: Whether the drug is contraindicated
        alerts: List of clinical alerts
        explanations: List of human-readable explanations for decisions
        dose_adjustment: Recommended dose modification (if any)
        risk_score: Overall risk score (0-100, where 100 is highest risk)
        triggered_rules: Names of rules that were triggered
    """

    contraindicated: bool = Field(default=False, description="Drug is contraindicated")
    alerts: list[Alert] = Field(default_factory=list, description="Clinical alerts")
    explanations: list[str] = Field(default_factory=list, description="Decision explanations")
    dose_adjustment: Optional[DoseAdjustment] = Field(None, description="Dose adjustment recommendation")
    risk_score: int = Field(default=0, ge=0, le=100, description="Overall risk score (0-100)")
    triggered_rules: list[str] = Field(default_factory=list, description="Rules that fired")

    def add_alert(self, message: str, severity: AlertSeverity, rule_name: str, category: str):
        """Add an alert to the decision context."""
        self.alerts.append(Alert(
            message=message,
            severity=severity,
            rule_name=rule_name,
            category=category
        ))
        self.triggered_rules.append(rule_name)

    def add_explanation(self, explanation: str):
        """Add an explanation to the decision context."""
        self.explanations.append(explanation)

    def set_contraindicated(self, reason: str):
        """Mark drug as contraindicated."""
        self.contraindicated = True
        self.add_explanation(f"CONTRAINDICATED: {reason}")

    def set_dose_adjustment(self, adjusted_dose: str, reason: str, original_dose: Optional[str] = None):
        """Set dose adjustment recommendation."""
        self.dose_adjustment = DoseAdjustment(
            original_dose=original_dose,
            adjusted_dose=adjusted_dose,
            reason=reason
        )
        self.add_explanation(f"Dose adjustment: {adjusted_dose}. Reason: {reason}")

    def calculate_risk_score(self):
        """Calculate overall risk score based on alerts."""
        score = 0
        for alert in self.alerts:
            if alert.severity == AlertSeverity.CRITICAL:
                score += 40
            elif alert.severity == AlertSeverity.HIGH:
                score += 25
            elif alert.severity == AlertSeverity.MODERATE:
                score += 15
            elif alert.severity == AlertSeverity.LOW:
                score += 5

        self.risk_score = min(score, 100)

    class Config:
        json_schema_extra = {
            "example": {
                "contraindicated": True,
                "alerts": [
                    {
                        "message": "QTc > 500ms - High risk of torsade de pointes",
                        "severity": "critical",
                        "rule_name": "HighQTcRule",
                        "category": "cardiac"
                    }
                ],
                "explanations": [
                    "CONTRAINDICATED: QTc exceeds safe threshold (520ms > 500ms)",
                    "Patient has severe QT prolongation"
                ],
                "risk_score": 85,
                "triggered_rules": ["HighQTcRule"]
            }
        }
