"""chat message logic change

Revision ID: 10a1211bb719
Revises: 83744cbb6448
Create Date: 2026-04-05 22:20:08.393808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a1211bb719'
down_revision: Union[str, Sequence[str], None] = '83744cbb6448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('session_id', sa.String(), nullable=False), schema='app')
    op.add_column('chat', sa.Column('user_id', sa.String(), nullable=False), schema='app')
    op.drop_index(op.f('ix_app_chat_chat_id'), table_name='chat', schema='app')
    op.create_index(op.f('ix_app_chat_user_id'), 'chat', ['user_id'], unique=False, schema='app')
    op.create_foreign_key(None, 'chat', 'users', ['user_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_column('chat', 'chat_id', schema='app')
    op.drop_column('chat', 'id', schema='app')
    op.add_column('patient_diagnoses', sa.Column('diagnosis_id', sa.String(), nullable=False), schema='app')
    op.drop_column('patient_diagnoses', 'id', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_diagnoses', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False), schema='app')
    op.drop_column('patient_diagnoses', 'diagnosis_id', schema='app')
    op.add_column('chat', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False), schema='app')
    op.add_column('chat', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='app')
    op.drop_constraint(None, 'chat', schema='app', type_='foreignkey')
    op.drop_index(op.f('ix_app_chat_user_id'), table_name='chat', schema='app')
    op.create_index(op.f('ix_app_chat_chat_id'), 'chat', ['chat_id'], unique=False, schema='app')
    op.drop_column('chat', 'user_id', schema='app')
    op.drop_column('chat', 'session_id', schema='app')
    # ### end Alembic commands ###
