"""add_chat_primary_key

Revision ID: 2b7db5ef9719
Revises: 48ad3954fccc
Create Date: 2026-04-08 00:35:52.950658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7db5ef9719'
down_revision: Union[str, Sequence[str], None] = '48ad3954fccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First, check if there are existing records - if so, truncate the table
    # Since this is early development and chat table has no critical data
    conn = op.get_bind()
    conn.execute(sa.text("TRUNCATE TABLE app.chat"))
    
    # Create a sequence for the id column
    conn.execute(sa.text("CREATE SEQUENCE app.chat_id_seq"))
    
    # Now add the id column with NOT NULL since table is empty
    # Set the default to use the sequence
    op.add_column('chat', sa.Column('id', sa.Integer(), nullable=False, server_default=sa.text("nextval('app.chat_id_seq')")), schema='app')
    
    # Set the sequence ownership to the column
    conn.execute(sa.text("ALTER SEQUENCE app.chat_id_seq OWNED BY app.chat.id"))
    
    op.create_primary_key('pk_app_chat', 'chat', ['id'], schema='app')
    op.alter_column('chat', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='app')
    op.create_index(op.f('ix_app_chat_session_id'), 'chat', ['session_id'], unique=False, schema='app')
    op.create_index('ix_chat_session', 'chat', ['session_id', 'created_at'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_session', table_name='chat', schema='app')
    op.drop_index(op.f('ix_app_chat_session_id'), table_name='chat', schema='app')
    op.alter_column('chat', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='app')
    op.drop_constraint('pk_app_chat', 'chat', type_='primary', schema='app')
    op.drop_column('chat', 'id', schema='app')
    
    # Drop the sequence
    conn = op.get_bind()
    conn.execute(sa.text("DROP SEQUENCE IF EXISTS app.chat_id_seq"))
    # ### end Alembic commands ###
