"""v013

Revision ID: 48ad3954fccc
Revises: e5f08ee0b50a
Create Date: 2026-04-08 00:29:05.193876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ad3954fccc'
down_revision: Union[str, Sequence[str], None] = 'e5f08ee0b50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if index exists before creating
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = inspector.get_indexes('users', schema='app')
    index_names = [idx['name'] for idx in indexes]
    
    if 'ix_app_users_email' not in index_names:
        op.create_index(op.f('ix_app_users_email'), 'users', ['email'], unique=True, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_users_email'), table_name='users', schema='app')
    # ### end Alembic commands ###
