"""include mimic

Revision ID: 83744cbb6448
Revises: 9085a97fd90b
Create Date: 2026-04-05 12:59:19.328689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83744cbb6448'
down_revision: Union[str, Sequence[str], None] = '9085a97fd90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_icd_diagnoses',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('icd9_code', sa.String(length=10), nullable=False),
    sa.Column('short_title', sa.String(length=50), nullable=True),
    sa.Column('long_title', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('row_id'),
    schema='mimiciii'
    )
    op.create_index(op.f('ix_mimiciii_d_icd_diagnoses_icd9_code'), 'd_icd_diagnoses', ['icd9_code'], unique=False, schema='mimiciii')
    op.create_table('d_labitems',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('itemid', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('fluid', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('loinc_code', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('row_id'),
    schema='mimiciii'
    )
    op.create_index(op.f('ix_mimiciii_d_labitems_itemid'), 'd_labitems', ['itemid'], unique=True, schema='mimiciii')
    op.create_table('patients',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('dod', sa.DateTime(), nullable=True),
    sa.Column('dod_hosp', sa.DateTime(), nullable=True),
    sa.Column('dod_ssn', sa.DateTime(), nullable=True),
    sa.Column('expire_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('subject_id'),
    schema='mimiciii'
    )
    op.create_table('admissions',
    sa.Column('hadm_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('admittime', sa.DateTime(), nullable=True),
    sa.Column('dischtime', sa.DateTime(), nullable=True),
    sa.Column('deathtime', sa.DateTime(), nullable=True),
    sa.Column('admission_type', sa.String(length=50), nullable=True),
    sa.Column('admission_location', sa.String(length=50), nullable=True),
    sa.Column('discharge_location', sa.String(length=50), nullable=True),
    sa.Column('insurance', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('ethnicity', sa.String(length=200), nullable=True),
    sa.Column('diagnosis', sa.String(length=255), nullable=True),
    sa.Column('hospital_expire_flag', sa.Integer(), nullable=True),
    sa.Column('has_chartevents_data', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['mimiciii.patients.subject_id'], ),
    sa.PrimaryKeyConstraint('hadm_id'),
    schema='mimiciii'
    )
    op.create_index(op.f('ix_mimiciii_admissions_subject_id'), 'admissions', ['subject_id'], unique=False, schema='mimiciii')
    op.create_table('labevents',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('hadm_id', sa.Integer(), nullable=True),
    sa.Column('itemid', sa.Integer(), nullable=False),
    sa.Column('charttime', sa.DateTime(), nullable=True),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('valuenum', sa.Float(), nullable=True),
    sa.Column('valueuom', sa.String(length=20), nullable=True),
    sa.Column('flag', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['itemid'], ['mimiciii.d_labitems.itemid'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['mimiciii.patients.subject_id'], ),
    sa.PrimaryKeyConstraint('row_id'),
    schema='mimiciii'
    )
    op.create_index('ix_mimic_lab_hadm', 'labevents', ['hadm_id'], unique=False, schema='mimiciii')
    op.create_index('ix_mimic_lab_itemid', 'labevents', ['itemid'], unique=False, schema='mimiciii')
    op.create_index('ix_mimic_lab_subject', 'labevents', ['subject_id'], unique=False, schema='mimiciii')
    op.create_index(op.f('ix_mimiciii_labevents_itemid'), 'labevents', ['itemid'], unique=False, schema='mimiciii')
    op.create_index(op.f('ix_mimiciii_labevents_subject_id'), 'labevents', ['subject_id'], unique=False, schema='mimiciii')
    op.create_table('diagnoses_icd',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('hadm_id', sa.Integer(), nullable=False),
    sa.Column('seq_num', sa.Integer(), nullable=True),
    sa.Column('icd9_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['hadm_id'], ['mimiciii.admissions.hadm_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['mimiciii.patients.subject_id'], ),
    sa.PrimaryKeyConstraint('row_id'),
    schema='mimiciii'
    )
    op.create_index('ix_mimic_diag_hadm', 'diagnoses_icd', ['hadm_id'], unique=False, schema='mimiciii')
    op.create_index('ix_mimic_diag_icd9', 'diagnoses_icd', ['icd9_code'], unique=False, schema='mimiciii')
    op.create_index('ix_mimic_diag_subject', 'diagnoses_icd', ['subject_id'], unique=False, schema='mimiciii')
    op.create_index(op.f('ix_mimiciii_diagnoses_icd_hadm_id'), 'diagnoses_icd', ['hadm_id'], unique=False, schema='mimiciii')
    op.create_index(op.f('ix_mimiciii_diagnoses_icd_subject_id'), 'diagnoses_icd', ['subject_id'], unique=False, schema='mimiciii')
    op.create_table('icustays',
    sa.Column('icustay_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('hadm_id', sa.Integer(), nullable=True),
    sa.Column('intime', sa.DateTime(), nullable=True),
    sa.Column('outtime', sa.DateTime(), nullable=True),
    sa.Column('los', sa.Integer(), nullable=True),
    sa.Column('first_careunit', sa.String(length=20), nullable=True),
    sa.Column('last_careunit', sa.String(length=20), nullable=True),
    sa.Column('first_wardid', sa.Integer(), nullable=True),
    sa.Column('last_wardid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hadm_id'], ['mimiciii.admissions.hadm_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['mimiciii.patients.subject_id'], ),
    sa.PrimaryKeyConstraint('icustay_id'),
    schema='mimiciii'
    )
    op.create_index(op.f('ix_mimiciii_icustays_hadm_id'), 'icustays', ['hadm_id'], unique=False, schema='mimiciii')
    op.create_index(op.f('ix_mimiciii_icustays_subject_id'), 'icustays', ['subject_id'], unique=False, schema='mimiciii')
    op.create_table('prescriptions',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('hadm_id', sa.Integer(), nullable=False),
    sa.Column('icustay_id', sa.Integer(), nullable=True),
    sa.Column('startdate', sa.DateTime(), nullable=True),
    sa.Column('enddate', sa.DateTime(), nullable=True),
    sa.Column('drug_type', sa.String(length=100), nullable=True),
    sa.Column('drug', sa.String(length=100), nullable=True),
    sa.Column('drug_name_poe', sa.String(length=100), nullable=True),
    sa.Column('drug_name_generic', sa.String(length=100), nullable=True),
    sa.Column('formulary_drug_cd', sa.String(length=120), nullable=True),
    sa.Column('route', sa.String(length=120), nullable=True),
    sa.Column('dose_val_rx', sa.String(length=120), nullable=True),
    sa.Column('dose_unit_rx', sa.String(length=120), nullable=True),
    sa.Column('form_val_disp', sa.String(length=120), nullable=True),
    sa.Column('form_unit_disp', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['hadm_id'], ['mimiciii.admissions.hadm_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['mimiciii.patients.subject_id'], ),
    sa.PrimaryKeyConstraint('row_id'),
    schema='mimiciii'
    )
    op.create_index('ix_mimic_rx_hadm', 'prescriptions', ['hadm_id'], unique=False, schema='mimiciii')
    op.create_index('ix_mimic_rx_subject', 'prescriptions', ['subject_id'], unique=False, schema='mimiciii')
    op.create_index(op.f('ix_mimiciii_prescriptions_hadm_id'), 'prescriptions', ['hadm_id'], unique=False, schema='mimiciii')
    op.create_index(op.f('ix_mimiciii_prescriptions_subject_id'), 'prescriptions', ['subject_id'], unique=False, schema='mimiciii')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mimiciii_prescriptions_subject_id'), table_name='prescriptions', schema='mimiciii')
    op.drop_index(op.f('ix_mimiciii_prescriptions_hadm_id'), table_name='prescriptions', schema='mimiciii')
    op.drop_index('ix_mimic_rx_subject', table_name='prescriptions', schema='mimiciii')
    op.drop_index('ix_mimic_rx_hadm', table_name='prescriptions', schema='mimiciii')
    op.drop_table('prescriptions', schema='mimiciii')
    op.drop_index(op.f('ix_mimiciii_icustays_subject_id'), table_name='icustays', schema='mimiciii')
    op.drop_index(op.f('ix_mimiciii_icustays_hadm_id'), table_name='icustays', schema='mimiciii')
    op.drop_table('icustays', schema='mimiciii')
    op.drop_index(op.f('ix_mimiciii_diagnoses_icd_subject_id'), table_name='diagnoses_icd', schema='mimiciii')
    op.drop_index(op.f('ix_mimiciii_diagnoses_icd_hadm_id'), table_name='diagnoses_icd', schema='mimiciii')
    op.drop_index('ix_mimic_diag_subject', table_name='diagnoses_icd', schema='mimiciii')
    op.drop_index('ix_mimic_diag_icd9', table_name='diagnoses_icd', schema='mimiciii')
    op.drop_index('ix_mimic_diag_hadm', table_name='diagnoses_icd', schema='mimiciii')
    op.drop_table('diagnoses_icd', schema='mimiciii')
    op.drop_index(op.f('ix_mimiciii_labevents_subject_id'), table_name='labevents', schema='mimiciii')
    op.drop_index(op.f('ix_mimiciii_labevents_itemid'), table_name='labevents', schema='mimiciii')
    op.drop_index('ix_mimic_lab_subject', table_name='labevents', schema='mimiciii')
    op.drop_index('ix_mimic_lab_itemid', table_name='labevents', schema='mimiciii')
    op.drop_index('ix_mimic_lab_hadm', table_name='labevents', schema='mimiciii')
    op.drop_table('labevents', schema='mimiciii')
    op.drop_index(op.f('ix_mimiciii_admissions_subject_id'), table_name='admissions', schema='mimiciii')
    op.drop_table('admissions', schema='mimiciii')
    op.drop_table('patients', schema='mimiciii')
    op.drop_index(op.f('ix_mimiciii_d_labitems_itemid'), table_name='d_labitems', schema='mimiciii')
    op.drop_table('d_labitems', schema='mimiciii')
    op.drop_index(op.f('ix_mimiciii_d_icd_diagnoses_icd9_code'), table_name='d_icd_diagnoses', schema='mimiciii')
    op.drop_table('d_icd_diagnoses', schema='mimiciii')
    # ### end Alembic commands ###
