"""init

Revision ID: 9085a97fd90b
Revises: 
Create Date: 2026-04-05 12:49:40.420112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9085a97fd90b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_chat_chat_id'), 'chat', ['chat_id'], unique=False, schema='app')
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('api_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_users_email'), 'users', ['email'], unique=True, schema='app')
    op.create_table('patient_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dob', 'sex', name='uq_patient_user_identity'),
    schema='app'
    )
    op.create_index(op.f('ix_app_patient_profiles_user_id'), 'patient_profiles', ['user_id'], unique=False, schema='app')
    op.create_table('staff_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_staff_profiles_user_id'), 'staff_profiles', ['user_id'], unique=True, schema='app')
    op.create_table('med_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_blob_url', sa.String(length=512), nullable=True),
    sa.Column('uploaded_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['app.patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_med_documents_document_type'), 'med_documents', ['document_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_med_documents_patient_id'), 'med_documents', ['patient_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_med_documents_user_id'), 'med_documents', ['user_id'], unique=False, schema='app')
    op.create_index('ix_patient_doc_created', 'med_documents', ['patient_id', 'created_at'], unique=False, schema='app')
    op.create_index('ix_patient_doc_type', 'med_documents', ['patient_id', 'document_type'], unique=False, schema='app')
    op.create_table('patient_diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('diagnosis_code_icd', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['app.patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_patient_diagnoses_diagnosis_code_icd'), 'patient_diagnoses', ['diagnosis_code_icd'], unique=False, schema='app')
    op.create_index(op.f('ix_app_patient_diagnoses_patient_id'), 'patient_diagnoses', ['patient_id'], unique=False, schema='app')
    op.create_index('ix_patient_diagnosis_code', 'patient_diagnoses', ['diagnosis_code_icd'], unique=False, schema='app')
    op.create_index('ix_patient_diagnosis_patient', 'patient_diagnoses', ['patient_id'], unique=False, schema='app')
    op.create_table('patient_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['app.patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_patient_files_patient_id'), 'patient_files', ['patient_id'], unique=False, schema='app')
    op.create_index('ix_patient_file_created', 'patient_files', ['patient_id', 'created_at'], unique=False, schema='app')
    op.create_table('patient_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['app.patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_patient_history_kind'), 'patient_history', ['kind'], unique=False, schema='app')
    op.create_index(op.f('ix_app_patient_history_occurred_at'), 'patient_history', ['occurred_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_patient_history_patient_id'), 'patient_history', ['patient_id'], unique=False, schema='app')
    op.create_index('ix_patient_kind', 'patient_history', ['patient_id', 'kind'], unique=False, schema='app')
    op.create_index('ix_patient_occurred', 'patient_history', ['patient_id', 'occurred_at'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patient_occurred', table_name='patient_history', schema='app')
    op.drop_index('ix_patient_kind', table_name='patient_history', schema='app')
    op.drop_index(op.f('ix_app_patient_history_patient_id'), table_name='patient_history', schema='app')
    op.drop_index(op.f('ix_app_patient_history_occurred_at'), table_name='patient_history', schema='app')
    op.drop_index(op.f('ix_app_patient_history_kind'), table_name='patient_history', schema='app')
    op.drop_table('patient_history', schema='app')
    op.drop_index('ix_patient_file_created', table_name='patient_files', schema='app')
    op.drop_index(op.f('ix_app_patient_files_patient_id'), table_name='patient_files', schema='app')
    op.drop_table('patient_files', schema='app')
    op.drop_index('ix_patient_diagnosis_patient', table_name='patient_diagnoses', schema='app')
    op.drop_index('ix_patient_diagnosis_code', table_name='patient_diagnoses', schema='app')
    op.drop_index(op.f('ix_app_patient_diagnoses_patient_id'), table_name='patient_diagnoses', schema='app')
    op.drop_index(op.f('ix_app_patient_diagnoses_diagnosis_code_icd'), table_name='patient_diagnoses', schema='app')
    op.drop_table('patient_diagnoses', schema='app')
    op.drop_index('ix_patient_doc_type', table_name='med_documents', schema='app')
    op.drop_index('ix_patient_doc_created', table_name='med_documents', schema='app')
    op.drop_index(op.f('ix_app_med_documents_user_id'), table_name='med_documents', schema='app')
    op.drop_index(op.f('ix_app_med_documents_patient_id'), table_name='med_documents', schema='app')
    op.drop_index(op.f('ix_app_med_documents_document_type'), table_name='med_documents', schema='app')
    op.drop_table('med_documents', schema='app')
    op.drop_index(op.f('ix_app_staff_profiles_user_id'), table_name='staff_profiles', schema='app')
    op.drop_table('staff_profiles', schema='app')
    op.drop_index(op.f('ix_app_patient_profiles_user_id'), table_name='patient_profiles', schema='app')
    op.drop_table('patient_profiles', schema='app')
    op.drop_index(op.f('ix_app_users_email'), table_name='users', schema='app')
    op.drop_table('users', schema='app')
    op.drop_index(op.f('ix_app_chat_chat_id'), table_name='chat', schema='app')
    op.drop_table('chat', schema='app')
    # ### end Alembic commands ###
