"""optional keys

Revision ID: e5f08ee0b50a
Revises: 10a1211bb719
Create Date: 2026-04-05 23:02:36.369041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f08ee0b50a'
down_revision: Union[str, Sequence[str], None] = '10a1211bb719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_profiles', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='app')
    op.alter_column('staff_profiles', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_profiles', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='app')
    op.alter_column('patient_profiles', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='app')
    # ### end Alembic commands ###
